# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.7.0

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
      - run: npm install

      # Download and cache dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:13.7.0

    steps:
      - checkout    

      - run: echo $NODE_ENV
      - run: npm install
      - run: npm test
       
  deploy:
    docker:
      - image: circleci/node:13.7.0

    steps:
      - checkout

      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:4cd245e6-b476-4b96-9156-1cadb402f9a5@git.heroku.com/codeconcept-beta.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master